services:
  - type: web
    name: crypto-trading-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class eventlet -w 1 --bind 0.0.0.0:$PORT wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: DEFAULT_EXCHANGE
        value: mexc
      - key: PAPER_TRADING
        value: true
